name: ci

on:
  pull_request:
    branches: [main, next]
  push:
    branches: [main, next]

jobs:
  vitest:
    name: 'Vitest (Vite 8)'

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - name: Install project dependencies
        run: pnpm i

      - name: Install playwright browser
        working-directory: examples/vite-8
        run: pnpm exec playwright install chromium

      - name: Run tests
        working-directory: examples/vite-8
        run: pnpm run test
